# Copyright 2022 - 2023 Weidmueller Interface GmbH & Co. KG <oss@weidmueller.com>
#
# SPDX-License-Identifier: MIT

FROM nginx:alpine-slim
COPY testdata/test-uc-addon-provide-ui-b/@0.1.0/index.html /usr/share/nginx/html/index.html
