# Copyright 2023 Weidmueller Interface GmbH & Co. KG <oss@weidmueller.com>
#
# SPDX-License-Identifier: MIT

FROM nginx:alpine-slim
COPY testdata/posuma/test-uc-addon-posuma/@0.1.0/index.html /usr/share/nginx/html/index.html
