# Copyright 2022 - 2023 Weidmueller Interface GmbH & Co. KG <oss@weidmueller.com>
#
# SPDX-License-Identifier: MIT

version: "3.8"
services:
  uc-aom:
    entrypoint: ./scripts/docker-entrypoint.sh
    environment:
      - GRPC_SERVER_URI=uc-aom:3800
      - RUN_MODE=${RUN_MODE:-dev}
      - ROOT_ACCESS_CONFIG_FILE=/tmp/root-access-config.json
    ports:
      - 3800:3800
    volumes:
      - localcatalog:/var/lib/uc-aom
      - remotecatalog:/var/run/uc-aom
      - cache:/var/cache/uc-aom
      - proxyroutes:/var/lib/nginx:rw
      - swupdate:/tmp
      - ${PWD}/scripts/root-access/configure-root-access.sh:/usr/sbin/configure-root-access.sh
      - ${PWD}/scripts/root-access/root-access-config.json:/tmp/root-access-config.json
      - /var/lib/uc-aom/volumes-public:/var/lib/uc-aom/volumes-public
    tmpfs:
      - /var/lib/uc-iam/permissions:exec
      - /go/src/uc-aom/volatile:exec
    tty: true
    depends_on:
      - "swupdate"

  grpcwebproxy:
    image: scarmuega/grpcwebproxy
    entrypoint:
      - grpcwebproxy
      - --allow_all_origins
      - --backend_addr=uc-aom:3800
      - --run_tls_server=false
      - --server_http_debug_port=9090
      - --server_http_max_read_timeout=0
      - --server_http_max_write_timeout=0
    ports:
      - "9090:9090"

  nginx:
    image: nginx:1.20.1-alpine
    container_name: uc-aom-nginx
    volumes:
      - ../nginx:/etc/nginx:ro
      - proxyroutes:/var/lib/nginx:ro
      - localcatalog:/var/lib/uc-aom:ro
      - remotecatalog:/var/run/uc-aom:ro
    ports:
      - "8080:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  swupdate:
    build: ../swupdate
    command: swupdate -v 
      --webserver "--port 8090 --document-root /usr/share/swupdate/www" 
      --suricatta "--nocheckcert --polldelay 5 --tenant default --url hawkbit:${HAWKBIT_PORT} --id swupdatedocker --gatewaytoken ${GATEWAYTOKEN}"
    tty: true
    volumes:
      - cache:/var/cache/uc-aom
      - swupdate:/tmp
    ports:
      - "8090:8090"
    depends_on:
      - "hawkbit"

  hawkbit:
    labels:
      - com.host.description=hawkbit
    image: hawkbit/hawkbit-update-server:latest
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port": "${HAWKBIT_PORT}",
        "hawkbit.dmf.rabbitmq.enabled":"false",
        "hawkbit.server.ddi.security.authentication.gatewaytoken.enabled":"true",
        "hawkbit.server.ddi.security.authentication.gatewaytoken.key": "${GATEWAYTOKEN}",
        "hawkbit.controller.pollingTime":"00:00:05",
        "hawkbit.controller.minPollingTime":"00:00:05"
        }'
    ports:
      - "${HAWKBIT_PORT}:${HAWKBIT_PORT}"

volumes:
  localcatalog:
  remotecatalog:
  proxyroutes:
  cache:
  swupdate:
